[package]
name = "filepath-complete"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow    = "1.0"
inquire   = "0.6"
simplelog = "0.12.1"
log = "0.4"
dyn-clone = "1.0"
home = "0.5"